name: Test

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.10'

      - run: |
          go test ./bot
          go test ./handler
          go test ./persistence
          go test ./slack
          go build ./example/connector.go
          go build ./example/eventsapi.go
